Class FLIP.Classes.DiagnosticCategory Extends %Persistent
{

Property Code As %String;

Property Desription As %String;

Property System As %String;

Storage Default
{
<Data name="DiagnosticCategoryDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Code</Value>
</Value>
<Value name="3">
<Value>Desription</Value>
</Value>
<Value name="4">
<Value>System</Value>
</Value>
</Data>
<DataLocation>^FLIP.Classes.DiagnosticCA7B3D</DataLocation>
<DefaultData>DiagnosticCategoryDefaultData</DefaultData>
<ExtentSize>0</ExtentSize>
<IdLocation>^FLIP.Classes.DiagnosticCA7B3D</IdLocation>
<IndexLocation>^FLIP.Classes.DiagnosticCA7B3I</IndexLocation>
<StreamLocation>^FLIP.Classes.DiagnosticCA7B3S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
